version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FinancialService
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: FinancialDataService.Api/Dockerfile  # Path to the Dockerfile
    ports:
      - "19901:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=FinancialService;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["dotnet", "run", "--project", "FinancialService.Api"]
